export default {
    HANDLE_CLICK: 'HANDLE_CLICK',
    SET_ADULT: 'SET_ADULT',
    SET_CHILD: 'SET_CHILD',
    PUSH_STATE: 'PUSH_STATE',
    FETCH_STATE: 'FETCH_STATE',
    START_FAKE_ASYNC: 'START_FAKE_ASYNC',
    RESET_DATA: 'RESET_DATA'
}