export default {
    HANDLE_CLICK: 'HANDLE_CLICK',
    SET_ADULT: 'SET_ADULT',
    SET_CHILD: 'SET_CHILD',
    DEHYDRATE_STATE: 'DEHYDRATE_STATE',
    HYDRATE_STATE: 'HYDRATE_STATE',
    START_FAKE_ASYNC: 'START_FAKE_ASYNC'
}